part of 'models.dart';

class FeedbackModel {
  late final String? title,
      branchName,
      address,
      troubleFeedbackId,
      troubleNoIndex,
      upsBrand,
      model,
      serialNumber,
      factoryProd,
      upsCapacity,
      upsCover,
      inputUps,
      inputPln,
      outputUps,
      load,
      assesmentDate,
      storeHead,
      store,
      snmpCard,
      epo,
      conditionBatt1,
      conditionBatt2,
      conditionBatt3,
      conditionBatt4,
      voltageBatt1,
      voltageBatt2,
      voltageBatt3,
      voltageBatt4,
      plnInstallation,
      cableSize,
      stdCable,
      stabilizer,
      mcb,
      stabilizerCapacity,
      mcbCapacity,
      surgeArrester,
      roomTemperature,
      grounding,
      panelInstallation,
      commUpsBatt1,
      commUpsBatt2,
      commUpsBatt3,
      commUpsBatt4,
      saranPerbaikan,
      isSolved,
      reason,
      photo,
      video,
      videoDescription,
      signature,
      signatureName,
      signatureTech1,
      nameTech1,
      signatureTech2,
      nameTech2,
      userInput,
      userUpdate,
      createdAt;

  FeedbackModel({
    this.title,
    this.branchName,
    this.address,
    this.troubleFeedbackId,
    this.troubleNoIndex,
    this.upsBrand,
    this.model,
    this.serialNumber,
    this.factoryProd,
    this.upsCapacity,
    this.upsCover,
    this.inputUps,
    this.inputPln,
    this.outputUps,
    this.load,
    this.assesmentDate,
    this.storeHead,
    this.store,
    this.snmpCard,
    this.epo,
    this.conditionBatt1,
    this.conditionBatt2,
    this.conditionBatt3,
    this.conditionBatt4,
    this.voltageBatt1,
    this.voltageBatt2,
    this.voltageBatt3,
    this.voltageBatt4,
    this.plnInstallation,
    this.cableSize,
    this.stdCable,
    this.stabilizer,
    this.mcb,
    this.stabilizerCapacity,
    this.mcbCapacity,
    this.surgeArrester,
    this.roomTemperature,
    this.grounding,
    this.panelInstallation,
    this.commUpsBatt1,
    this.commUpsBatt2,
    this.commUpsBatt3,
    this.commUpsBatt4,
    this.saranPerbaikan,
    this.isSolved,
    this.reason,
    this.photo,
    this.video,
    this.videoDescription,
    this.signature,
    this.signatureName,
    this.signatureTech1,
    this.nameTech1,
    this.signatureTech2,
    this.nameTech2,
    this.userInput,
    this.userUpdate,
    this.createdAt,
  });

  FeedbackModel.fromJson(Map<String, dynamic> json)
      : title = json['title'] ?? "",
        branchName = json['branch_name'] ?? "",
        address = json['address'] ?? "",
        troubleFeedbackId = json['trouble_feedback_id'] ?? "",
        troubleNoIndex = json['trouble_no_index'] ?? "",
        upsBrand = json['ups_brand'] ?? "",
        model = json['model'] ?? "Not set",
        serialNumber = json['serial_number'] ?? "Not set",
        factoryProd = json['factory_prod'] ?? "",
        upsCapacity = json['ups_capacity'] ?? "",
        upsCover = json['ups_cover'] ?? "",
        inputUps = json['input_ups'] ?? "",
        inputPln = json['input_pln'] ?? "",
        outputUps = json['output_ups'] ?? "",
        load = json['load'] ?? "",
        assesmentDate = json['assesment_date'] ?? "",
        storeHead = json['store_head'] ?? "",
        store = json['store'] ?? "",
        snmpCard = json['snmp_card'] ?? "",
        epo = json['epo'] ?? "",
        conditionBatt1 = json['condition_batt_1'] ?? "",
        conditionBatt2 = json['condition_batt_2'] ?? "",
        conditionBatt3 = json['condition_batt_3'] ?? "",
        conditionBatt4 = json['condition_batt_4'] ?? "",
        voltageBatt1 = json['voltage_batt_1'] ?? "",
        voltageBatt2 = json['voltage_batt_2'] ?? "",
        voltageBatt3 = json['voltage_batt_3'] ?? "",
        voltageBatt4 = json['voltage_batt_4'] ?? "",
        plnInstallation = json['pln_installation'] ?? "",
        cableSize = json['cable_size'] ?? "",
        stdCable = json['std_cable'] ?? "",
        stabilizer = json['stabilizer'] ?? "",
        mcb = json['mcb'] ?? "",
        stabilizerCapacity = json['stabilizer_capacity'] ?? "",
        mcbCapacity = json['mcb_capacity'] ?? "",
        surgeArrester = json['surge_arrester'] ?? "",
        roomTemperature = json['room_temperature'] ?? "",
        grounding = json['grounding'] ?? "",
        panelInstallation = json['panel_installation'] ?? "",
        commUpsBatt1 = json['comm_ups_batt_1'] ?? "",
        commUpsBatt2 = json['comm_ups_batt_2'] ?? "",
        commUpsBatt3 = json['comm_ups_batt_3'] ?? "",
        commUpsBatt4 = json['comm_ups_batt_4'] ?? "",
        saranPerbaikan = json['saran_perbaikan'] ?? "",
        isSolved = json['is_solved'] ?? "",
        reason = json['reason'] ?? "",
        photo = json['photo'] ?? "",
        video = json['video'] ?? "",
        videoDescription = json['video_description'] ?? "",
        signature = json['signature'] ?? "",
        signatureName = json['signature_name'] ?? "",
        signatureTech1 = json['signature_tech1'] ?? "",
        nameTech1 = json['name_tech1'] ?? "",
        signatureTech2 = json['signature_tech2'] ?? "",
        nameTech2 = json['name_tech2'] ?? "",
        userInput = json['user_input'] ?? "",
        userUpdate = json['user_update'] ?? "",
        createdAt = json['created_at'] ?? "";

  Map<String, dynamic> toJson() => {
        'title': title,
        'branch_name': branchName,
        'address': address,
        'trouble_feedback_id': troubleFeedbackId,
        'trouble_no_index': troubleNoIndex,
        'ups_brand': upsBrand,
        'model': model,
        'serial_number': serialNumber,
        'factory_prod': factoryProd,
        'ups_capacity': upsCapacity,
        'ups_cover': upsCover,
        'input_ups': inputUps,
        'input_pln': inputPln,
        'output_ups': outputUps,
        'load': load,
        'assesment_date': assesmentDate,
        'store_head': storeHead,
        'store': store,
        'snmp_card': snmpCard,
        'epo': epo,
        'condition_batt_1': conditionBatt1,
        'condition_batt_2': conditionBatt2,
        'condition_batt_3': conditionBatt3,
        'condition_batt_4': conditionBatt4,
        'voltage_batt_1': voltageBatt1,
        'voltage_batt_2': voltageBatt2,
        'voltage_batt_3': voltageBatt3,
        'voltage_batt_4': voltageBatt4,
        'pln_installation': plnInstallation,
        'cable_size': cableSize,
        'std_cable': stdCable,
        'stabilizer': stabilizer,
        'mcb': mcb,
        'stabilizer_capacity': stabilizerCapacity,
        'mcb_capacity': mcbCapacity,
        'surge_arrester': surgeArrester,
        'room_temperature': roomTemperature,
        'grounding': grounding,
        'panel_installation': panelInstallation,
        'comm_ups_batt_1': commUpsBatt1,
        'comm_ups_batt_2': commUpsBatt2,
        'comm_ups_batt_3': commUpsBatt3,
        'comm_ups_batt_4': commUpsBatt4,
        'saran_perbaikan': saranPerbaikan,
        'is_solved': isSolved,
        'reason': reason,
        'photo': photo,
        'video': video,
        'video_description': videoDescription,
        'signature': signature,
        'signature_name': signatureName,
        'signature_tech1': signatureTech1,
        'name_tech1': nameTech1,
        'signature_tech2': signatureTech2,
        'name_tech2': nameTech2,
        'user_input': userInput,
        'user_update': userUpdate,
        'created_at': createdAt,
      };
}
