part of 'models.dart';

class TroubleModel {
  late final String? troubleId,
      troubleNo,
      title,
      description,
      troubleCategoryCode,
      technisianId,
      customerCode,
      picName,
      latt,
      long,
      address,
      areaCode,
      phoneNumber,
      rowState,
      video,
      prPhoto,
      isSolved,
      reason,
      userInput,
      reqTime,
      createdAt,
      custName,
      rowStateName,
      categoryName,
      technicianName,
      baseLatt,
      baseLong,
      baseName,
      baseAddress;

  int distance;

  String file;

  TroubleModel(
      this.troubleId,
      this.troubleNo,
      this.title,
      this.description,
      this.troubleCategoryCode,
      this.technisianId,
      this.customerCode,
      this.picName,
      this.latt,
      this.long,
      this.address,
      this.areaCode,
      this.phoneNumber,
      this.rowState,
      this.video,
      this.file,
      this.prPhoto,
      this.isSolved,
      this.reason,
      this.userInput,
      this.reqTime,
      this.createdAt,
      this.custName,
      this.rowStateName,
      this.categoryName,
      this.technicianName,
      this.baseLatt,
      this.baseLong,
      this.baseName,
      this.baseAddress,
      this.distance);

  TroubleModel.fromJson(Map<String, dynamic> json)
      : troubleId = json['trouble_id'],
        troubleNo = json['trouble_no'],
        title = json['title'],
        description = json['description'],
        troubleCategoryCode = json['trouble_categories_code'],
        technisianId = json['technician_id'],
        customerCode = json['customer_code'] ?? "Not set",
        picName = json['pic_name'] ?? "Not set",
        latt = json['lat'] ?? "",
        long = json['long'] ?? "",
        address = json['address'] ?? "",
        areaCode = json['area_code'],
        phoneNumber = json['phone_number'],
        rowState = json['rowstate'],
        video = json['video'] ?? "",
        file = json['file'] ?? "",
        prPhoto = json['pr_photo'] ?? "",
        isSolved = json['is_solved'],
        reason = json['reason'],
        userInput = json['user_input'],
        reqTime = json['requested_time'],
        createdAt = json['created_at'],
        custName = json['cust_name'],
        rowStateName = json['rowstate_name'],
        categoryName = json['categories_name'],
        technicianName = json['technician_name'],
        baseLatt = json['area_lat'] ?? "",
        baseLong = json['area_long'] ?? "",
        baseName = json['area_name'],
        baseAddress = json['area_address'],
        distance = json['distance'] ?? 15;

  Map<String, dynamic> toJson() => {
        'trouble_id': troubleId,
        'trouble_no': troubleNo,
        'title': title,
        'description': description,
        'trouble_categories_code': troubleCategoryCode,
        'technician_id': technisianId,
        'customer_code': customerCode,
        'pic_name': picName,
        'lat': latt,
        'long': long,
        'address': address,
        'area_code': areaCode,
        'phone_number': phoneNumber,
        'rowstate': rowState,
        'video': video,
        'file': file,
        'pr_photo': prPhoto,
        'is_solved': isSolved,
        'reason': reason,
        'user_input': userInput,
        'requested_time': reqTime,
        'created_at': createdAt,
        'cust_name': custName,
        'rowstate_name': rowStateName,
        'categories_name': categoryName,
        'technician_name': technicianName,
        'area_lat': baseLatt,
        'area_long': baseLong,
        'area_name': baseName,
        'area_address': baseAddress,
        'distance': distance,
      };
}
